global:
  scrape_interval: 10s   # fr√©quence de scrape
  evaluation_interval: 10s

scrape_configs:
  - job_name: "coursedjango"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets:
          - "coursedjango.onrender.com"
